"""Embed precompiled model programs so game startup needs no shader compiler."""
from pathlib import Path
import sys
folder = Path(sys.argv[1])
output = Path(sys.argv[2])
parts = ['// Generated by tools/embed-upscaling-shaders.py. Do not edit.', '#pragma once', '#include <cstddef>',
         'namespace NeuralShaders {', 'struct Blob { const unsigned char* data; size_t size; };']
for path in sorted(folder.glob('*.cso')):
    name = path.stem.replace('-', '_')
    contents = path.read_bytes()
    parts.append(f'alignas(4) inline constexpr unsigned char {name}_bytes[] = {{')
    for i in range(0, len(contents), 24):
        parts.append(','.join(str(b) for b in contents[i:i+24]) + ',')
    parts += ['};', f'inline constexpr Blob {name} = {{{name}_bytes, sizeof({name}_bytes)}};']
for quality, groups in [('fast', [2,2,1,1]), ('balanced', [3,3,2,1])]:
    names = [f'{quality}_{i}_{j}' for i,n in enumerate(groups) for j in range(n)]
    parts.append(f'inline constexpr Blob {quality}[] = {{{",".join(names)}}};')
parts.append('}')
output.write_text('\n'.join(parts), encoding='utf-8')
